server {
    listen 80;
    server_name _;

 # Folder where frontend files are stored
    root /usr/share/nginx/html;

    # Default file to load
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}